#General Hyper Parameters:
# gpu_id: '0,1,2,3,4,5,6,7'
use_gpu: True

#Training Hyper Parameters:
epochs: 300
learner: adam
eval_step: 1
stopping_step: 10
clip_grad_norm: {'max_norm': 5.0, 'norm_type': 2}
shuffle: False

# TODO 这里我也暂时的将scheduler关掉
# scheduler
# scheduler: True
scheduler: True
warm_up_ratio: 0.1

# data setting
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
user_inter_num_interval: "[5, inf)"
item_inter_num_interval: "[5, inf)"
load_col: {
    inter: [user_id, item_id, rating, timestamp]
    }


#Evaluation Hyper Parameters:
eval_args:
  group_by: user
  order: TO
  split: {'LS': 'valid_and_test'}
  mode: 'full'
repeatable: True
metrics: ['Hit', 'NDCG', 'MRR']
topk: [1, 5, 10, 20]
valid_metric: Hit@20
valid_metric_bigger: True
eval_batch_size: 4096
metric_decimal_place: 4

#Other Hyper Parameters:
initializer_range: 0.02

# 用于加速模型
enable_amp: True
enable_scaler: True
worker: 8
